from torchsketch.utils.data_augmentation_utils.randomly_convert_stroke_width_4_svg import randomly_convert_stroke_width_4_svg
from torchsketch.utils.data_augmentation_utils.randomly_remove_strokes_4_svg import randomly_remove_strokes_4_svg
from torchsketch.utils.data_augmentation_utils.remove_strokes_4_svg import remove_strokes_4_svg
from torchsketch.utils.data_augmentation_utils.rotate_sketch_picture import rotate_sketch_picture